
POST http://localhost:8080/api/productos
Content-Type: application/json

{
  "nombre": "Bocadillo Veleño Premium",
  "precio": 3500,
  "cantidad": 20
}
###
GET http://localhost:8080/api/productos
###
PUT http://localhost:8080/api/productos/14
Content-Type: application/json
 
 {
  "nombre": "Bocadillo Veleño Extra Grande",
  "precio": 4500,
  "cantidad": 50
}
###
DELETE http://localhost:8080/api/productos/14


### PRUEBA ERROR 404
GET http://localhost:8080/api/productos/999


### PRUEBA ERROR 400
POST http://localhost:8080/api/productos
Content-Type: application/json

{
  "precio": "tres mil"
}

### PRUEBA ERROR 405
PATCH http://localhost:8080/api/productos/14

### 1. Registrar un nuevo usuario (Éxito - 201)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nombre": "Dayana Barbosa",
  "email": "dayana2@gmail.com",
  "password": "123"
}













### 2. Registrar el mismo usuario (Error - 400)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nombre": "Dayana Barbosa",
  "email": "dayana2@gmail.com",
  "password": "123"
}

### 3. Iniciar sesión (Éxito - 200)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "dayana2@gmail.com",
  "password": "123"
}

### 4. Iniciar sesión con clave errónea (Error - 401)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "dayana2@gmail.com",
  "password": "clave_incorrecta"
}